apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: crypto-price-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crypto-price-service
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
